name: imalabya
recipe: drupal9
config:
  webroot: web
  php: "8.0"
  xdebug: false
services:
  database:
    type: mariadb:10.4
    creds:
      user: drupal
      password: drupal
      database: drupal
